name: Deploy React app to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Download your repository
      - name: Checkout
        uses: actions/checkout@v6

      # 2. Install Node.js
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: npm

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build React/Vite
      - name: Build
        run: npm run build

      # 5. Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v6

      # 6. Upload the dist folder
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist

      # 7. Deploy to GitHub Pages
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5
